### ISSUE TITLE
resume err TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by bambooDu** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#192]
"ezuikit-js": "^7.7.10"； 
8.0版本会出现 [https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/issues/174](url)
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/54257610/d732f696-aed8-4ed5-8e07-130ca4b38262)
在实例化后 如图初始化播放器完成下 点击themeData iconId: 'play' 的播放按钮会出现如下错误；手动调用实例 play方法， 这个播放切换按钮功能就正常了；
resume err TypeError: Cannot read properties of undefined (reading 'indexOf')
    at eval (ezuikit.js:13:1)
    at new Promise (<anonymous>)
    at e.value (ezuikit.js:13:1)
    at eval (ezuikit.js:13:1)
    at new Promise (<anonymous>)
    at e.value (ezuikit.js:13:1)
    at e.eval (ezuikit.js:13:1)
    at e.s (ezuikit.js:1:1)
ezuikit.js:13 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at eval (ezuikit.js:13:1)
    at new Promise (<anonymous>)
    at e.value (ezuikit.js:13:1)
    at eval (ezuikit.js:13:1)
    at new Promise (<anonymous>)
    at e.value (ezuikit.js:13:1)
    at e.eval (ezuikit.js:13:1)
    at e.s (ezuikit.js:1:1)

**Comment by bambooDu** [comment]
> "ezuikit-js": "^7.7.10"； 8.0版本会出现 [https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/issues/174](url) ![image](https://private-user-images.githubusercontent.com/54257610/321212542-d732f696-aed8-4ed5-8e07-130ca4b38262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjcyODgsIm5iZiI6MTcxMjgyNjk4OCwicGF0aCI6Ii81NDI1NzYxMC8zMjEyMTI1NDItZDczMmY2OTYtYWVkOC00ZWQ1LThlMDctMTMwY2E0YjM4MjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA5MTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYWYzMTM3NGMyZDY0YmU2NmI4ZDFmMTgyNTZlN2NlNTMwM2YwZjMzNDZhY2U4NDZlMWU3MTgyOGI4ZWE4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V_0fWh0sbBZQB2RHdO30E5i6MPa92h_adtnjSnWhD5k) 在实例化后 如图初始化播放器完成下 点击themeData iconId: 'play' 的播放按钮会出现如下错误；手动调用实例 play方法， 这个播放切换按钮功能就正常了； resume err TypeError: Cannot read properties of undefined (reading 'indexOf') at eval (ezuikit.js:13:1) at new Promise () at e.value (ezuikit.js:13:1) at eval (ezuikit.js:13:1) at new Promise () at e.value (ezuikit.js:13:1) at e.eval (ezuikit.js:13:1) at e.s (ezuikit.js:1:1) ezuikit.js:13 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf') at eval (ezuikit.js:13:1) at new Promise () at e.value (ezuikit.js:13:1) at eval (ezuikit.js:13:1) at new Promise () at e.value (ezuikit.js:13:1) at e.eval (ezuikit.js:13:1) at e.s (ezuikit.js:1:1)
