### ISSUE TITLE
作者大大，发现一个bug. 开发环境对讲功能可以正常使用，打包只会使用对讲功能会报错 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL at ezuikit-js-D8yxrFM6.js:2:2502423

### ISSUE THREAD

**Issue by ZhouJieLunJay** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#224]
发现一个bug. 开发环境对讲功能可以正常使用，打包只会使用对讲功能会报错 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL at ezuikit-js-D8yxrFM6.js:2:2502423

我的node版本：v20.14.0 pnpm版本:9.2.0 ezuikit-js版本：8.0.5

**Comment by freeshineit** [comment]
> 发现一个bug. 开发环境对讲功能可以正常使用，打包只会使用对讲功能会报错 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL at ezuikit-js-D8yxrFM6.js:2:2502423
> 
> 我的node版本：v20.14.0 pnpm版本:9.2.0 ezuikit-js版本：8.0.5

我看了一下源码 ，没匹配到你说的那个错误， 可以截一下报错信息的图吗？
8.0.8 版本 修复了一下相关的问题  不知道能不能解决你说的问题 你可以试一下 最新版本

**Comment by ZhouJieLunJay** [comment]
新版本没有这个报错了，但是还是本地开发时可以正常使用对讲功能，打包上线之后就使用不了对讲功能

**Comment by ZhouJieLunJay** [comment]
我使用的是 node：v20.14.0     vue3+vite+ts

**Comment by ong1303261** [comment]
我也发现了这个问题，请问你解决了吗？

**Comment by freeshineit** [comment]
> 我也发现了这个问题，请问你解决了吗？

你安装一下 8.1.9-beta.3

**Comment by ong1303261** [comment]
我用的环境是react 17.0.2

**Comment by ong1303261** [comment]
我使用的 
react 17.0.2
node 14.17.0
ezuikit-js版本：8.1.5

我发现的问题是 本地发消息有一个socket连接 “wss://webrtc.ys7.com/rtcgw-ws”
部署到测试服务没有这个 socket，怀疑是Nginx配置问题，折腾半天没有发现问题在哪里。
然后说安装最新版本"8.1.9-beta.3" 更新后有各种引入报错

ERROR in ./node_modules/ezuikit-js/index.mjs 45:2682595-2682596
Can't import the named export 'isMobile' from non EcmaScript module (only default export is available)

说是非正式版本要引入资源，但是如何引入非正式版本的资源。

**Comment by freeshineit** [comment]
> 我使用的 react 17.0.2 node 14.17.0 ezuikit-js版本：8.1.5
> 
> 我发现的问题是 本地发消息有一个socket连接 “wss://webrtc.ys7.com/rtcgw-ws” 部署到测试服务没有这个 socket，怀疑是Nginx配置问题，折腾半天没有发现问题在哪里。 然后说安装最新版本"8.1.9-beta.3" 更新后有各种引入报错
> 
> ERROR in ./node_modules/ezuikit-js/index.mjs 45:2682595-2682596 Can't import the named export 'isMobile' from non EcmaScript module (only default export is available)
> 
> 说是非正式版本要引入资源，但是如何引入非正式版本的资源。

引用 ezuikit-js/index.js  文件试一下
