### ISSUE TITLE
Uncaught runtime errors: × ERROR window.JSPlayerModule is not a function TypeError: window.JSPlayerModule is not a function

### ISSUE THREAD

**Issue by bluefok** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#262]
Uncaught runtime errors:
×
ERROR
window.JSPlayerModule is not a function
TypeError: window.JSPlayerModule is not a function
    at I.onload (webpack-internal:///../../node_modules/.pnpm/ezuikit-js@8.0.12/node_modules/ezuikit-js/ezuikit.js:101:1023187)
    at manualInvokeElementOnLoad (webpack-internal:///../../node_modules/.pnpm/qiankun@2.10.16/node_modules/qiankun/es/sandbox/patchers/dynamicAppend/common.js:109:13)
    at success (webpack-internal:///../../node_modules/.pnpm/qiankun@2.10.16/node_modules/qiankun/es/sandbox/patchers/dynamicAppend/common.js:271:19)
    at schedule (webpack-internal:///../../node_modules/.pnpm/import-html-entry@1.17.0/node_modules/import-html-entry/esm/index.js:339:11)
    at eval (webpack-internal:///../../node_modules/.pnpm/import-html-entry@1.17.0/node_modules/import-html-entry/esm/index.js:346:14)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///../../node_modules/.pnpm/import-html-entry@1.17.0/node_modules/import-html-entry/esm/index.js:345:12)

**Comment by freeshineit** [comment]
微服务中把静态资源(ezuikit_static)可以放置在 主应用中， 然后在子应用中设置 staticPath
